storage:
  model:
    class: 'storage/model/model'
    defaultApiAction: 'load'
    apiActions:
      load:
        description: 'Get model data'
      update:
        description: 'Update model'
        params: 
          values:
            type: 'json'
            description: 'Update model'
      delete:
        description: 'Delete model'
