.play:
  .gameChronicles:
    class: storage/storage
    forceUuids: true
    providerConfig:
      collection: chronicles
    schema:
      fields:
        gameId:
          code: gameId
          title: Game ID
          type:
            name: link
            storageId: play.games
        type:
          code: type # record / event
          title: Type
          type:
            name: string
        turn:
          code: turn
          title: Turn
          type: 
            name: number
        content:
          code: content
          title: Content
          type:
            name: string
            textArea: true
  .games:
    model:
      .chronicle:
        class: play/games/chronicle/chronicle
        forceUuids: true
        schema:
          provider: play.gameChronicles
        providerConfig:
          collection: chronicles
          
