.content:
  .templateParams:
    class: storage/storage
    forceUuids: true
    providerConfig:
      collection: templateParams
    schema:
      fields:
        templateId:
          code: templateId
          title: Template Id
          type:
            name: link
            storageId: content.templates
        title:
          code: title
          title: Title
          type:
            name: string
        code:
          code: code
          title: Code
          type:
            name: string
        type:
          code: type
          title: Type
          type:
            name: json
  .templates:
    model:
      .params:
        class: storage/storage
        forceUuids: true
        forceMyParentIdInModels: values.templateId
        providerConfig:
          collection: templateParams
        schema:
          provider: content.templateParams