.content:
  .templateParams:
    class: 'storage/storage'
    forceUuids: true
    providerConfig:
      collection: 'templateParams'
    schema:
      templateId:
        code: 'templateId'
        title: 'Template Id'
        type:
          name: 'string'
      title:
        code: 'title'
        title: 'Title'
        type:
          name: 'string'
      code:
        code: 'code'
        title: 'Code'
        type:
          name: 'string'
      type:
        code: 'type'
        title: 'Type'
        type:
          name: 'json'

