.play:
  .gameChatTelegram:
    class: play/telegram/gameChat
    apiActions:
      start:
        description: Creates player
      help:
        description: Displays help
      end_game:
        description: Ends current game if there is one
        params:
          playerModel:
            required: true
            description: Player model
            type: model
      next:
        description: Generate next chronicle
        params:
          gameModel:
            required: true
            description: Game model
            type: model
      new_game:
        description: Starts new game
        params:
          playerModel:
            required: true
            description: Player model
            type: model
      new_scenario:
        description: Starts new game with scenario ID (advanced usage)
        params:
          playerModel:
            required: true
            description: Player model
            type: model
