requiredModules:
  worlds/stories: true
  # worlds/players: true
  # worlds/chats: true

.worlds:
  .variables:
    class: storage/storage
    forceUuids: true
    providerConfig:
      collection: worldVariables
    schema:
      fields:
        worldId:
          code: worldId
          title: World Id
          type:
            name: link
            storageId: worlds
        name:
          code: name
          title: Name
          type:
            name: string
        value:
          code: value
          title: Value
          type:
            name: string
  class: storage/storage
  forceUuids: true
  providerConfig:
    collection: worlds
  schema:
    fields:
      title:
        code: title
        title: Title
        type:
          name: string
      scenarioId:
        code: scenarioId
        title: Scenario Id
        type:
          name: link
          storageId: content.templates.scenarios.objects
      turn:
        code: turn
        title: Turn number
        type:
          name: number
  model:
    class: 'worlds/world'
    apiActions:
      nextTurn:
        description: Jumps to next turn
    .variables:
      class: storage/storage
      forceUuids: true
      providerConfig:
        collection: worldVariables
      schema:
        provider: worlds.variables
