.characters:
  class: storage/storage
  forceUuids: true
  providerConfig:
    collection: characters
  schema:
    fields:
      storyId:
        code: storyId
        title: Story ID
        type:
          name: string
      characterRoleId:
        code: characterTypeId
        title: Characted Type
        type:
          name: link
          storageId: content.templates.characterTypes.objects
      name:
        code: name
        title: Name
        type: 
          name: string
      bio:
        code: bio
        title: Bio
        type:
          name: string
          textArea: true
      chatId:
        code: chatId
        title: Chat Id
        type:
          name: link
          storageId: chats

.worlds:
  model:
    .stories:
      model:
        .characters:
          class: storage/storage
          providerConfig:
            collection: characters
          forceUuids: true
          schema:
            provider: characters
          forceMyParentIdInModels: values.storyId
          model:
            class: worlds/stories/characters/character
            apiActions:
              say:
                description: Say to character
                params: 
                  message:
                    type: 
                      name: string
                    description: Phrase to say
