requiredModules:
  play/games/chronicle: true
  play/games/agents: true

.play:
  class: dweller
  .games:
    class: play/games/games
    apiActions:
      newGame:
        description: Starts new game
        params:
          scenarioId:
            required: true
            description: 'Model of the game'
            type: string
          cityName:
            description: 'City name'
            type: string
          playerId:
            description: 'Player Id'
            type: string
    providerConfig:
      collection: games
    forceUuids: true
    schema:
      fields:
        started:
          code: started
          title: Started
          type:
            name: number # time
        finished:
          code: finished
          title: Finished
          type:
            name: number # time
        scenarioId:
          code: scenarioId
          title: Scenario Id
          type:
            name: string
        chancellorChatId:
          code: chancellorChatId
          title: Chancellor chat
          type: 
            name: link
            storageId: play.chats
        cityName:
          code: cityName
          title: City name
          type:
            name: string
        cityDescription:
          code: cityDescription
          title: City description
          type:
            name: string
        playerId:
          code: playerId
          title: Player Id
          type:
            name: string
        turn:
          code: turn
          title: Turn
          type:
            name: number
    model:
      class: play/games/game
      apiActions: 
        next:
          description: Get to next chronicle
        sayToChancellor:
          description: Calls chancellor
          params:
            text:
              code: text
              title: Text
              type:
                name: string
        setCityName:
          description: Sets city name
          params:
            name:
              code: name
              title: Name
              type:
                name: string
