.shards:
  .gameMessages:
    class: storage/storage
    forceUuids: true
    providerConfig:
      collection: gameMessages
    schema:
      fields:
        gameId:
          code: gameId
          title: Game Id
          type:
            name: string
        agentId:
          code: agentId
          title: Agent Id
          type:
            name: string
        role:
          code: role
          title: Role
          type:
            name: string
        content:
          code: content
          title: Content
          type:
            name: content
