traits:
  mongoProvider:
    src: core/mongo/provider
    dwellerConfig:
      db: test_refactor
  mongoConsumer:
    src: core/mongo/consumer
    dwellerConfig:
      dbProvider: mongo

.mongo:
  requiredTraits:
    mongoProvider: true
