requiredModules:
  storage: true

.storage:
  .users:
    class: 'users/users'
    .getId:
      class: 'users/commands/getId'
      params: 
        paramName:
          type: 'int'
          description: 'Some description'
          required: true
