requiredModules:
  worlds/stories/records: true
  worlds/stories/storyteller: true
  worlds/stories/characters: true

.stories:
  class: storage/storage
  providerConfig:
    collection: stories
  forceUuids: true
  schema:
    fields:
      started:
        code: started
        title: Started
        type:
          name: number # time
      finished:
        code: finished
        title: Finished
        type:
          name: number # time
      playerId:
        code: playerId
        title: Player Id
        type:
          name: string
      worldId:
        code: worldId
        title: World
        type: 
          name: link
          storageId: worlds
      turn:
        code: turn
        title: Turn
        type:
          name: number
      name:
        code: name
        title: Name
        type:
          name: string
      seed:
        code: seed
        title: Seed
        type:
          name: string
          textArea: true
.worlds:
  model:
    .stories:
      class: storage/storage
      providerConfig:
        collection: stories
      forceUuids: true
      forceMyParentIdInModels: values.worldId
      schema:
        provider: stories
      model:
        class: worlds/stories/story
        apiActions:
          start:
            description: Starts the game
