# requiredModules:
#   play/games/chronicle: true
#   play/games/agents: true

.worlds:
  model:
    .stories:
      .variables:
        class: storage/storage
        forceUuids: true
        providerConfig:
          collection: storyVariables
        schema:
          fields:
            worldId:
              code: storyId
              title: Story Id
              type:
                name: link
                storageId: worlds.stories
            name:
              code: name
              title: Name
              type:
                name: string
            value:
              code: value
              title: Value
              type:
                name: string
      class: storage/storage
      providerConfig:
        collection: stories
      forceUuids: true
      schema:
        fields:
          started:
            code: started
            title: Started
            type:
              name: number # time
          finished:
            code: finished
            title: Finished
            type:
              name: number # time
          # chancellorChatId:
          #   code: chancellorChatId
          #   title: Chancellor chat
          #   type: 
          #     name: link
          #     storageId: play.chats
          playerId:
            code: playerId
            title: Player Id
            type:
              name: string
      model:
        class: worlds/stories/story
        .variables:
          class: storage/storage
          forceUuids: true
          providerConfig:
            collection: storyVariables
          schema:
            provider: world.stories.variables
