.play:
  .players:
    class: storage/storage
    providerConfig:
      collection: players
    schema:
      objectTitleField: telegramUsername
      fields:
        gameId:
          code: gameId
          title: Game Id
          type:
            name: link
            storageId: play.games
        telegramId:
          code: telegramId
          title: Telegram ID
          type:
            name: string
        telegramNick:
          code: telegramUsername
          title: Telegram Nick
          type:
            name: string
        preferredModel:
          code: preferredModel
          title: Preferred game model
          type:
            name: string
        inNewGameCreation:
          code: inNewGameCreation
          title: In new game creation
          type:
            name: bool
     