requiredModules:
  content/templates: true
  content/templateParams: true
  content/construct: true

.content:
  class: content/content
  apiActions:
    dump:
      description: Dumps content
    restore:
      description: Restores content
      params: 
        content:
          type: json
          description: Content to restore
