requiredModules:
  content/templates/objects: true

.content:
  .templates:
    class: content/templates/templates
    apiActions:
      createTemplate:
        params:
          templateId:
            type: string
            description: New template ID
      create: false
    providerConfig:
      collection: templates
    schema:
      objectTitle: '{title}'
      fields:
        title:
          code: title
          title: Title
          type:
            name: string
        objectTitle:
          code: objectTitle
          title: Object title
          type:
            name: string
        singleton:
          code: singleton
          title: Singleton
          type: 
            name: bool
        constructKeyField:
          code: constructKeyField
          title: Construct key field
          type: 
            name: link
            storageId: content.templateParams
  .objects:
    forceUuids: true
    class: storage/storage
    providerConfig:
      collection: objects
