requiredModules:
  storage/model: true

storage:
  defaultApiAction: getAll
  apiActions:
    getAll:
      description: Find models
      params: 
        query:
          type: json
          description: Query
    create:
      description: New model
      params: 
        values:
          type: json
          description: Fields
    getSchema:
      description: Get storage schema
