.content:
  class: modules/content/content
  apiActions:
    dump:
      description: Dumps content
    restore:
      description: Restores content
      params: 
        content:
          type: json
          description: Content to restore
  .templateParams:
    class: core/storage/storage
    forceUuids: true
    providerConfig:
      collection: templateParams
    schema:
      fields:
        templateId:
          code: templateId
          title: Template Id
          type:
            name: link
            storageId: content.templates
        title:
          code: title
          title: Title
          type:
            name: string
        code:
          code: code
          title: Code
          type:
            name: string
        type:
          code: type
          title: Type
          type:
            name: json
  .templates:
    class: modules/content/templates
    apiActions:
      createTemplate:
        params:
          templateId:
            type:
              name: string
            description: New template ID
      create: false
    providerConfig:
      collection: templates
    schema:
      objectTitle: '{title}'
      fields:
        title:
          code: title
          title: Title
          type:
            name: string
        objectTitle:
          code: objectTitle
          title: Object title
          type:
            name: string
        singleton:
          code: singleton
          title: Singleton
          type:
            name: bool
        constructKeyField:
          code: constructKeyField
          title: Construct key field
          type:
            name: link
            storageId: content.templateParams
    model:
      .params:
        class: core/storage/storage
        forceUuids: true
        forceMyParentIdInModels: values.templateId
        providerConfig:
          collection: templateParams
        schema:
          provider: content.templateParams
      .objects:
        forceUuids: true
        class: modules/content/objects
        forceMyParentIdInModels: templateId
        providerConfig:
          collection: objects
  .objects:
    forceUuids: true
    class: core/storage/storage
    providerConfig:
      collection: objects
