requiredModules:
  modules/content: true
  core/mongo: true
  core/storage: true
  core/admin: true
  core/api: true
  core/projectConfig: true

.storageProviders:
  .mongo:
    db: test_project
  .mongoMemory:
    db: test_project

dweller:
  apiActions:
    help:
      description: Shows help
    getConfig:
      description: Shows config
