requiredModules:
  content: true
  mongo: true
  storage: true
  play: true
  llmProviders: true
  admin: true
  api: true

projects:
  test_project:
    .storageProviders:
      .mongo:
        db: test_project
      .mongoMemory:
        db: test_project
    telegramServers:
      main:
        id: main
        apiTokenKeyInEnv: TELEGRAM_API_TOKEN
        handlerId: play.gameChatTelegram
  cloudshire:
    .storageProviders:
        .mongo:
          db: cloudshire
        .mongoMemory:
          db: cloudshire
httpServer:
  urlMask: '/*/api/*'
