requiredModules:
  content: true
  mongo: true
  storage: true
  worlds: true
  llmProviders: true
  admin: true
  api: true
  chats: true
  projectConfig: true

.storageProviders:
  .mongo:
    db: test_project
  .mongoMemory:
    db: test_project

httpServer:
  urlMask: '/*/api/*'
  
dweller:
  apiActions:
    help:
      description: Shows help
    getConfig:
      description: Shows config
