requiredModules:
  core/mongo: true
  core/api: true

# httpServer:
#   urlMask: '/*/api/*'
  
dweller:
  apiActions:
    help:
      description: Shows help
    getConfig:
      description: Shows config

requiredTraits:
  engine: true

traits:
  greeter:
    src: traits/greeter 
    dwellerConfig:
      greeting: Hello!
      apiActions:
        greet:
          description: Greets

.base:
  ownProp: 7
  requiredTraits:
    greeter: true
  .child:
    ownProp: 10
    requiredTraits: 
      greeter:
        greeting: Heya!
.second:
  requiredTraits:
    greeter:
      greeting: Good evening