.confluxes:
  class: storage/storage
  providerConfig:
    collection: confluxes
  forceUuids: true
  schema:
    fields:
      worldId:
        code: worldId
        title: World
        type:
          name: link
          storageId: worlds
      confluxTypeId:
        code: confluxTypeId
        title: Conflux Type
        type:
          name: link
          storageId: content.templates.confluxTypes.objects
      startTurn:
        code: startTurn
        title: Start turn
        type: number
      endTurn:
        code: endTurn
        title: End turn
        type: number

.worlds:
  model:
    .confluxes:
      class: storage/storage
      providerConfig:
        collection: confluxes
      forceUuids: true
      forceMyParentIdInModels: values.worldId
      schema:
        provider: confluxes
      model:
        class: worlds/stories/confluxes/conflux
        apiActions:
          start:
            description: Starts the conflux
          run:
            description: Generates next turn
        .records:
          class: storage/storage
          forceUuids: true
          providerConfig:
            collection: confluxRecords
          forceMyParentIdInModels: values.confluxId
          schema:
            fields:
              confluxId:
                code: confluxId
                title: Conflux ID
                type:
                  name: string
              turn:
                code: turn
                title: Turn
                type: 
                  name: number
              content:
                code: content
                title: Content
                type:
                  name: string
                  textArea: true
