.shards:
  .players:
    class: storage/storage
    providerConfig:
      collection: players
    schema:
      fields:
        gameId:
          code: gameId
          title: Game Id
          type:
            name: string
        telegramId:
          code: telegramId
          title: Telegram ID
          type:
            name: string
        telegramNick:
          code: telegramUsername
          title: Telegram Nick
          type:
            name: string
        preferredModel:
          code: preferredModel
          title: Preferred game model
          type:
            name: string
    model:
      class: shards/players/player
     