.shards:
  .players:
    class: storage/storage
    providerConfig:
      collection: players
    schema:
      fields:
        gameId:
          code: gameId
          title: Game Id
          type:
            name: string
        telegramId:
          code: telegramId
          title: Telegram ID
          type:
            name: string
        telegramNick:
          code: telegramUsername
          title: Telegram Nick
          type:
            name: string
    model:
      class: shards/players/player
      apiActions:
        start:
          description: Creates player
        next:
          description: Creates player
        addEvent:
          description: Creates player
          params:
            text:
              description: Event text
              type: string
        newGame:
          description: Starts new game
          params:
            cityName:
              required: true
              description: cityName
              type: string
